import type { AnyContentItem } from "./types";

const collectedAt = "2026-05-07T14:00:00-04:00";

export const contentItems: AnyContentItem[] = [
  {
    id: "news-local-visual-generator",
    slug: "local-visual-generator",
    title: "本地 SVG 生成器进入简报视觉工作流",
    original_title: "AI-brief local visual generator",
    summary: "AI-brief 可以用本地 SVG 生成器根据标题、类型、评分和标签生成封面图、流程图和视觉摘要，不需要付费 API。",
    one_sentence_takeaway: "简报视觉资产可以先由本地规则生成，重点是帮助判断，而不是追求昂贵的图像模型效果。",
    why_it_matters: "中文用户每天面对高密度 AI 信息，视觉摘要能降低理解成本，也能让 Playbook 更容易保存和复用。",
    content_type: "news",
    category: "models",
    tags: ["Multimodal", "Prompt", "Workflow"],
    target_audience: ["pm", "creator", "operator"],
    source_name: "AI-brief Local Generator",
    source_url: "https://example.com/local-visual-generator",
    canonical_url: "https://example.com/local-visual-generator",
    published_at: "2026-05-07",
    collected_at: collectedAt,
    language: "en",
    reading_time_minutes: 4,
    status: "published",
    readability_score: 86,
    impact_score: 87,
    actionability_score: 91,
    confidence_score: 92,
    difficulty: "beginner",
    recommended_action: "try",
    key_facts: ["适合生成和编辑图像", "需要对图中事实进行来源回查", "可转化为 Brief 封面和图解模板"],
    opportunities: ["生成每日简报视觉封面", "把模型对比转成图解", "为社媒分发生成统一素材"],
    risks: ["图像里的数字可能被误读为事实", "品牌素材和版权边界需要人工确认"],
    next_steps: ["定义视觉 Brief 模板", "为每张图绑定来源链接", "加入图像事实核对 checklist"],
    related_ids: ["guide-local-brief-assets", "article-visual-briefing-system"],
    news_scope: "model_release",
    affected_groups: ["pm", "creator", "operator"],
  },
  {
    id: "news-enterprise-agent-workflows",
    slug: "enterprise-agent-workflows",
    title: "企业 Agent 更新正在改变工具链判断",
    summary: "企业自动化从单点聊天转向浏览器、代码、文档和后台系统的组合工作流。",
    one_sentence_takeaway: "Agent 更新的关键不是新功能名称，而是它是否能稳定接入真实业务系统。",
    why_it_matters: "产品和开发团队需要重新评估工具权限、可观测性、失败恢复和成本。",
    content_type: "news",
    category: "agent",
    tags: ["Agent", "Workflow", "Business"],
    target_audience: ["developer", "pm", "enterprise"],
    source_name: "AI-brief Source Monitor",
    source_url: "https://example.com/enterprise-agent-workflows",
    published_at: "2026-05-07",
    collected_at: collectedAt,
    language: "zh",
    reading_time_minutes: 5,
    status: "published",
    readability_score: 80,
    impact_score: 89,
    actionability_score: 76,
    confidence_score: 74,
    difficulty: "intermediate",
    recommended_action: "read",
    key_facts: ["企业 Agent 依赖多个系统连接", "权限与审计比演示效果更重要", "稳定性需要用真实任务测试"],
    opportunities: ["把重复运营流程转成 Agent workflow", "建立工具调用评测集"],
    risks: ["权限过大导致误操作", "缺少日志会让失败难以复盘"],
    next_steps: ["列出一个真实流程", "定义成功标准", "记录失败模式"],
    related_ids: ["integration-mcp-permission-check", "guide-agent-workflow-eval"],
    news_scope: "product_update",
    affected_groups: ["developer", "pm", "enterprise"],
  },
  {
    id: "news-ai-risk-procurement",
    slug: "ai-risk-procurement",
    title: "AI 风险框架需要进入采购评估",
    summary: "AI 工具采购不能只看功能和价格，也要看数据流向、权限、审计、回滚和供应商可靠性。",
    one_sentence_takeaway: "AI 采购的判断标准正在从能不能用，升级到能不能安全地持续使用。",
    why_it_matters: "企业采用 AI 工具时，错误权限和不可审计的数据流会放大组织风险。",
    content_type: "news",
    category: "safety",
    tags: ["Safety", "Business"],
    target_audience: ["enterprise", "pm", "founder"],
    source_name: "Governance Radar",
    source_url: "https://example.com/ai-risk-procurement",
    published_at: "2026-05-06",
    collected_at: collectedAt,
    language: "zh",
    reading_time_minutes: 4,
    status: "published",
    readability_score: 83,
    impact_score: 82,
    actionability_score: 72,
    confidence_score: 78,
    difficulty: "intermediate",
    recommended_action: "monitor",
    key_facts: ["采购评估需要纳入安全项", "权限、审计和数据边界是核心问题", "高风险工具不应默认自动发布到团队"],
    opportunities: ["建立 AI 工具采购 checklist", "把风险提示放入工具详情页"],
    risks: ["忽略审计会影响后续合规", "只看功能会低估数据风险"],
    next_steps: ["补充采购评分表", "标记高权限工具", "定义禁用和回滚流程"],
    related_ids: ["integration-mcp-permission-check", "course-enterprise-ai-adoption"],
    news_scope: "policy",
    affected_groups: ["enterprise", "founder", "pm"],
  },
  {
    id: "model-code-agent-radar",
    slug: "code-agent-model-radar",
    title: "代码 Agent 模型要同时看推理、工具调用和成本",
    summary: "代码任务不能只看榜单分数，必须把 repo 级任务、工具调用稳定性、延迟和成本放在一起评估。",
    one_sentence_takeaway: "代码 Agent 的模型选择应该由真实 repo 测试驱动。",
    why_it_matters: "模型迁移会影响开发效率、自动改代码的风险和 API 成本。",
    content_type: "model",
    category: "ai-coding",
    tags: ["AI Coding", "Agent", "Open Source"],
    target_audience: ["developer", "founder"],
    source_name: "AI-brief Model Radar",
    source_url: "https://artificialanalysis.ai/leaderboards/models",
    published_at: "2026-05-07",
    collected_at: collectedAt,
    language: "zh",
    reading_time_minutes: 6,
    status: "published",
    readability_score: 82,
    impact_score: 91,
    actionability_score: 78,
    confidence_score: 88,
    difficulty: "intermediate",
    recommended_action: "read",
    key_facts: ["榜单不等于业务表现", "工具调用失败率需要单独记录", "成本和延迟会影响 Agent 可用性"],
    opportunities: ["建立 repo 级模型评测", "为团队模型迁移做成本估算"],
    risks: ["单一 benchmark 会误导模型选择", "低价模型可能增加重试成本"],
    next_steps: ["选 3 个 repo 任务", "记录 tokens、延迟、成功率", "输出迁移建议"],
    related_ids: ["guide-model-migration-checklist", "course-ai-coding-builder"],
    model_provider: "multi-provider",
    primary_capability: "code reasoning",
    pricing_note: "需要按输入、输出、缓存和重试成本综合估算",
    latency_note: "Agent 场景对首 token 和工具调用往返都敏感",
    benchmark_notes: ["榜单可做初筛", "必须加入真实 repo 任务", "需要记录失败模式"],
    test_prompts: ["修复一个带测试的 bug", "解释跨文件调用链", "生成并运行迁移 checklist"],
  },
  {
    id: "model-long-context-chinese",
    slug: "long-context-chinese-models",
    title: "中文长文模型评估要看抽取、反驳和引用",
    summary: "长上下文模型适合行业报告和论文解读，但需要测试事实抽取、反方观点和引用一致性。",
    one_sentence_takeaway: "中文长文能力不是塞进更多 token，而是能否可靠提炼判断。",
    why_it_matters: "AI-brief 的深读和 Learn 推荐依赖长文理解质量。",
    content_type: "model",
    category: "research",
    tags: ["Research", "China", "RAG"],
    target_audience: ["researcher", "pm", "developer"],
    source_name: "AI-brief Model Radar",
    source_url: "https://example.com/long-context-models",
    published_at: "2026-05-07",
    collected_at: collectedAt,
    language: "zh",
    reading_time_minutes: 5,
    status: "published",
    readability_score: 84,
    impact_score: 80,
    actionability_score: 74,
    confidence_score: 73,
    difficulty: "intermediate",
    recommended_action: "monitor",
    key_facts: ["长上下文需要事实一致性测试", "中文术语和引用要单独验收", "适合报告和论文初筛"],
    opportunities: ["自动生成论文 TL;DR", "为深读内容加反方观点"],
    risks: ["引用错配会降低可信度", "过长输入增加成本"],
    next_steps: ["准备 5 篇中文长文", "测试引用抽取", "记录误读案例"],
    related_ids: ["paper-agent-memory-evals", "course-rag-engineer"],
    model_provider: "multi-provider",
    primary_capability: "long context analysis",
    pricing_note: "长输入成本需要按报告长度估算",
    latency_note: "长文分析可以异步处理，用户侧关注最终结构质量",
    benchmark_notes: ["上下文窗口不是充分条件", "引用一致性比摘要流畅度重要"],
    test_prompts: ["列出文中 7 个关键事实并给出处", "提出反方观点", "把报告转成 Playbook 草案"],
  },
  {
    id: "model-visual-briefing",
    slug: "visual-briefing-models",
    title: "视觉 Brief 模型要评估信息密度和事实可追溯",
    summary: "图像模型可以帮助生成 Brief 图解，但需要通过模板、来源绑定和人工复核控制误读。",
    one_sentence_takeaway: "视觉生成的价值在于帮助决策，而不是做漂亮封面。",
    why_it_matters: "AI-brief 需要把复杂信息转成能被快速扫描的视觉资产。",
    content_type: "model",
    category: "multimodal",
    tags: ["Multimodal", "Prompt", "Workflow"],
    target_audience: ["creator", "pm", "operator"],
    source_name: "AI-brief Local Generator",
    source_url: "https://example.com/local-visual-generator",
    published_at: "2026-05-07",
    collected_at: collectedAt,
    language: "en",
    reading_time_minutes: 4,
    status: "published",
    readability_score: 87,
    impact_score: 86,
    actionability_score: 90,
    confidence_score: 91,
    difficulty: "beginner",
    recommended_action: "try",
    key_facts: ["图像模型适合生成视觉解释", "数字事实需要回源", "模板会影响可读性"],
    opportunities: ["为每条 Brief 生成社媒图", "把模型对比做成图解"],
    risks: ["图像细节可能误导用户", "视觉风格可能压过判断信息"],
    next_steps: ["定义 Brief 图像模板", "加入来源水印", "人工复核关键数字"],
    related_ids: ["guide-local-brief-assets", "news-local-visual-generator"],
    model_provider: "OpenAI",
    primary_capability: "image generation",
    pricing_note: "按视觉资产生成量估算",
    latency_note: "适合后台生成，不必阻塞阅读页",
    benchmark_notes: ["重点看中文排版可读性", "重点看事实标注位置"],
    test_prompts: ["生成模型雷达封面", "把 3 条新闻转成一张图解", "生成 Playbook checklist 海报"],
  },
  {
    id: "tool-ai-coding-suite",
    slug: "ai-coding-suite",
    title: "AI Coding 工具要按写入权限和验证能力分级",
    summary: "Cursor、Codex、Claude Code 等工具的关键差异在于 repo 理解、命令执行、测试反馈和安全边界。",
    one_sentence_takeaway: "AI Coding 工具不是谁更会补全，而是谁能更安全地完成真实改动。",
    why_it_matters: "开发者和团队需要知道什么时候让工具读、写、运行命令或只做 review。",
    content_type: "tool",
    category: "ai-coding",
    tags: ["AI Coding", "Agent", "Workflow"],
    target_audience: ["developer", "founder"],
    source_name: "AI-brief Tools",
    source_url: "https://example.com/ai-coding-tools",
    published_at: "2026-05-07",
    collected_at: collectedAt,
    language: "zh",
    reading_time_minutes: 5,
    status: "published",
    readability_score: 85,
    impact_score: 88,
    actionability_score: 84,
    confidence_score: 76,
    difficulty: "intermediate",
    recommended_action: "try",
    key_facts: ["工具权限会改变风险", "测试反馈决定可用性", "review 模式和写入模式应分开"],
    opportunities: ["建立团队 AI coding SOP", "把常见任务变成 Playbook"],
    risks: ["误改代码", "运行命令产生副作用"],
    next_steps: ["先用只读 review", "再用小 repo 测试写入", "记录回滚方式"],
    related_ids: ["guide-agent-workflow-eval", "model-code-agent-radar"],
    product_url: "https://example.com/ai-coding-tools",
    maturity: "production_ready",
    installation_minutes: 10,
    alternatives: ["Cursor", "Codex", "Claude Code"],
  },
  {
    id: "tool-workflow-automation-stack",
    slug: "workflow-automation-stack",
    title: "n8n、Dify、LangGraph 适合不同自动化成熟度",
    summary: "低代码、应用编排和工程框架分别服务不同团队，不能用同一套标准评估。",
    one_sentence_takeaway: "Workflow 工具选择要先看团队能维护哪一种复杂度。",
    why_it_matters: "错误工具会让自动化流程难维护、难调试、难迁移。",
    content_type: "tool",
    category: "workflow",
    tags: ["Workflow", "Agent", "Business"],
    target_audience: ["operator", "developer", "pm"],
    source_name: "AI-brief Tools",
    source_url: "https://example.com/workflow-stack",
    published_at: "2026-05-06",
    collected_at: collectedAt,
    language: "zh",
    reading_time_minutes: 6,
    status: "published",
    readability_score: 82,
    impact_score: 83,
    actionability_score: 85,
    confidence_score: 72,
    difficulty: "intermediate",
    recommended_action: "read",
    key_facts: ["不同工具对应不同维护成本", "流程日志和重试机制很关键", "凭证管理不能后补"],
    opportunities: ["把运营流程自动化", "建立 Agent workflow 模板库"],
    risks: ["流程黑箱化", "凭证泄露", "重试导致重复发送"],
    next_steps: ["选一个低风险流程", "定义输入输出", "加入日志和回滚"],
    related_ids: ["guide-news-to-checklist", "news-enterprise-agent-workflows"],
    product_url: "https://example.com/workflow-stack",
    maturity: "usable",
    installation_minutes: 30,
    alternatives: ["n8n", "Dify", "LangGraph"],
  },
  {
    id: "tool-local-ai-runtime",
    slug: "local-ai-runtime",
    title: "本地 AI 运行时适合隐私敏感和低成本试验",
    summary: "Ollama、LM Studio、vLLM、llama.cpp 等适合本地模型试验，但部署、显存和模型质量需要单独评估。",
    one_sentence_takeaway: "Local AI 的优势是控制权，不是默认更省心。",
    why_it_matters: "企业和独立创造者会在隐私、成本和可控性之间做取舍。",
    content_type: "tool",
    category: "local-ai",
    tags: ["Local AI", "Open Source", "Safety"],
    target_audience: ["developer", "enterprise", "creator"],
    source_name: "AI-brief Tools",
    source_url: "https://example.com/local-ai-runtime",
    published_at: "2026-05-05",
    collected_at: collectedAt,
    language: "zh",
    reading_time_minutes: 5,
    status: "published",
    readability_score: 84,
    impact_score: 78,
    actionability_score: 82,
    confidence_score: 70,
    difficulty: "advanced",
    recommended_action: "save",
    key_facts: ["本地部署需要硬件预算", "模型质量和云端仍有差距", "隐私和延迟可控性更高"],
    opportunities: ["隐私敏感数据本地处理", "离线 demo 和原型"],
    risks: ["显存不足", "模型更新维护成本", "错误安全感"],
    next_steps: ["确认硬件配置", "选择一个量化模型", "跑最小 demo"],
    related_ids: ["course-rag-engineer", "model-long-context-chinese"],
    product_url: "https://example.com/local-ai-runtime",
    maturity: "usable",
    installation_minutes: 45,
    alternatives: ["Ollama", "LM Studio", "vLLM"],
  },
  {
    id: "project-open-source-agent-runtime",
    slug: "open-source-agent-runtime",
    title: "开源 Agent Runtime 需要先跑最小 demo",
    summary: "开源 Agent 项目看起来增长很快，但 README、issue、示例和权限边界决定真实可用性。",
    one_sentence_takeaway: "项目热度只能初筛，跑通 demo 才能判断是否可用。",
    why_it_matters: "Tools 栏目需要避免被 star 和营销误导。",
    content_type: "project",
    category: "open-source",
    tags: ["Open Source", "Agent", "AI Coding"],
    target_audience: ["developer", "founder"],
    source_name: "GitHub Trending",
    source_url: "https://github.com/trending",
    published_at: "2026-05-07",
    collected_at: collectedAt,
    language: "en",
    reading_time_minutes: 4,
    status: "published",
    readability_score: 78,
    impact_score: 76,
    actionability_score: 80,
    confidence_score: 68,
    difficulty: "advanced",
    recommended_action: "try",
    key_facts: ["README 和 demo 是可用性信号", "issue 响应反映维护健康度", "权限说明必须明确"],
    opportunities: ["发现早期开源工具", "形成安装成功率评分"],
    risks: ["依赖过多", "维护不稳定", "权限说明不足"],
    next_steps: ["跑最小 demo", "记录安装时间", "检查最近提交"],
    related_ids: ["tool-ai-coding-suite", "guide-agent-workflow-eval"],
    repository_url: "https://github.com/trending",
    maturity: "experimental",
    installation_minutes: 25,
    alternatives: ["OpenHands", "CrewAI", "AutoGen"],
  },
  {
    id: "integration-mcp-permission-check",
    slug: "mcp-permission-check",
    title: "MCP 权限检查 Playbook",
    summary: "MCP、Skill、Hooks 等集成内容必须明确接入对象、权限等级、测试命令和回滚方式。",
    one_sentence_takeaway: "Integration 的核心价值是连接能力和权限风险都讲清楚。",
    why_it_matters: "用户需要知道一个连接器能读什么、写什么、执行什么，以及失败后怎么恢复。",
    content_type: "integration",
    category: "mcp",
    tags: ["MCP", "Safety", "Workflow"],
    target_audience: ["developer", "operator"],
    source_name: "Model Context Protocol",
    source_url: "https://modelcontextprotocol.io/docs/getting-started/intro",
    published_at: "2026-05-07",
    collected_at: collectedAt,
    language: "en",
    reading_time_minutes: 5,
    status: "published",
    readability_score: 80,
    impact_score: 84,
    actionability_score: 89,
    confidence_score: 85,
    difficulty: "advanced",
    recommended_action: "save",
    key_facts: ["连接器需要最小权限", "写入和执行权限必须单独标记", "回滚方式要出现在详情页"],
    opportunities: ["建立 Integration 安全模板", "给 MCP 项目生成验证 checklist"],
    risks: ["写权限过大", "凭证泄露", "错误工具调用"],
    next_steps: ["列出读写边界", "跑最小权限测试", "记录回滚命令"],
    related_ids: ["news-ai-risk-procurement", "guide-mcp-local-files"],
    integration_target: "local files and tools",
    permission_level: "write",
    verification_methods: ["最小权限配置", "只读测试", "写入回滚测试"],
  },
  {
    id: "article-visual-briefing-system",
    slug: "visual-briefing-system",
    title: "视觉 Brief 应该服务判断而不是装饰",
    summary: "AI 简报里的图片需要承载结论、影响、行动和风险，而不是充当泛化插图。",
    one_sentence_takeaway: "一张好图应该让用户更快决定是否要读、试或保存。",
    why_it_matters: "这会决定 AI-brief 本地视觉生成器的产品边界。",
    content_type: "article",
    category: "product",
    tags: ["Multimodal", "Business", "Prompt"],
    target_audience: ["pm", "creator"],
    source_name: "AI-brief Editorial",
    source_url: "https://example.com/visual-briefing-system",
    published_at: "2026-05-07",
    collected_at: collectedAt,
    language: "zh",
    reading_time_minutes: 8,
    status: "published",
    readability_score: 88,
    impact_score: 77,
    actionability_score: 79,
    confidence_score: 72,
    difficulty: "beginner",
    recommended_action: "read",
    key_facts: ["视觉摘要必须包含判断信息", "图像需要来源绑定", "模板比单次生成更重要"],
    opportunities: ["形成可复用视觉规范", "让 Playbook 更容易传播"],
    risks: ["图片变成营销装饰", "弱化事实核查"],
    next_steps: ["定义封面图字段", "增加图像验收标准", "测试中文排版"],
    related_ids: ["news-local-visual-generator", "guide-local-brief-assets"],
    core_argument: "视觉层只有在提升判断效率时才是产品能力。",
    evidence_strength: "medium",
    counterpoints: ["文字摘要可能已经足够", "图像生成会增加审核成本"],
  },
  {
    id: "paper-agent-memory-evals",
    slug: "agent-memory-evals",
    title: "Agent Memory 论文需要转成可复现实验",
    summary: "Agent memory 相关论文值得关注，但 AI-brief 应优先提炼可复现实验、局限和适合场景。",
    one_sentence_takeaway: "论文价值不在摘要，而在能否变成可验证 workflow。",
    why_it_matters: "研究内容只有被转成实验步骤，才会对 builder 有持续价值。",
    content_type: "paper",
    category: "research",
    tags: ["Research", "Agent", "RAG"],
    target_audience: ["researcher", "developer"],
    source_name: "Hugging Face Papers",
    source_url: "https://huggingface.co/papers",
    published_at: "2026-05-06",
    collected_at: collectedAt,
    language: "en",
    reading_time_minutes: 12,
    status: "published",
    readability_score: 70,
    impact_score: 79,
    actionability_score: 66,
    confidence_score: 74,
    difficulty: "advanced",
    recommended_action: "read",
    key_facts: ["论文需要看方法和局限", "复现实验比结论摘要更重要", "可转 Guide 的论文价值更高"],
    opportunities: ["生成复现 checklist", "提炼 Agent memory eval 模板"],
    risks: ["实验设置和真实场景差距大", "过度解读 benchmark"],
    next_steps: ["提取方法", "列出复现实验输入", "评估是否可转 Playbook"],
    related_ids: ["model-long-context-chinese", "guide-agent-workflow-eval"],
    paper_url: "https://huggingface.co/papers",
    method_summary: "以任务上下文和历史状态评估 Agent memory 效果。",
    limitations: ["未覆盖企业权限场景", "真实工具调用成本不明确"],
    reproducibility: "partial",
  },
  {
    id: "guide-model-migration-checklist",
    slug: "model-migration-checklist",
    title: "判断一个新模型是否值得迁移",
    summary: "用 30 分钟把模型发布转成成本、延迟、质量和失败模式的迁移判断。",
    one_sentence_takeaway: "不要因为新模型发布就迁移，先跑三类真实任务。",
    why_it_matters: "模型迁移会影响成本、质量、用户体验和工程复杂度。",
    content_type: "guide",
    category: "models",
    tags: ["AI Coding", "Agent", "Workflow"],
    target_audience: ["developer", "pm"],
    source_name: "AI-brief Playbooks",
    source_url: "https://example.com/model-migration-checklist",
    published_at: "2026-05-07",
    collected_at: collectedAt,
    language: "zh",
    reading_time_minutes: 7,
    status: "published",
    readability_score: 90,
    impact_score: 88,
    actionability_score: 94,
    confidence_score: 80,
    difficulty: "intermediate",
    recommended_action: "use_now",
    key_facts: ["需要真实任务", "要同时记录质量和成本", "迁移结论要包含不迁移选项"],
    opportunities: ["降低模型切换风险", "形成团队评测模板"],
    risks: ["测试样本太少", "忽略边缘失败"],
    next_steps: ["选择 3 个任务", "跑新旧模型", "输出迁移建议"],
    related_ids: ["model-code-agent-radar", "model-long-context-chinese"],
    outcome: "得到是否迁移的明确结论",
    prerequisites: ["已有当前模型基线", "有 3 个真实任务样本"],
    prompts: ["请对比两个模型在这个 repo 任务中的失败模式。"],
    checklist: ["记录输入输出成本", "记录延迟", "记录失败原因", "写出迁移结论"],
    validation_methods: ["新模型在 3 个任务中至少 2 个胜出", "成本没有超过预算阈值", "失败模式可接受"],
  },
  {
    id: "guide-local-brief-assets",
    slug: "local-brief-assets",
    title: "用本地 SVG 生成简报视觉资产",
    summary: "把一条 AI Brief 转成本地生成的封面图、流程图或 checklist 海报，并保留来源核查步骤。",
    one_sentence_takeaway: "视觉生成必须围绕判断字段，而不是只追求好看。",
    why_it_matters: "图像资产能提高信息传播和保存价值，但也会放大事实错误。",
    content_type: "guide",
    category: "multimodal",
    tags: ["Multimodal", "Prompt", "Workflow"],
    target_audience: ["creator", "operator", "pm"],
    source_name: "AI-brief Playbooks",
    source_url: "https://example.com/local-brief-assets",
    published_at: "2026-05-07",
    collected_at: collectedAt,
    language: "zh",
    reading_time_minutes: 6,
    status: "published",
    readability_score: 92,
    impact_score: 86,
    actionability_score: 95,
    confidence_score: 82,
    difficulty: "beginner",
    recommended_action: "use_now",
    key_facts: ["视觉 prompt 要包含主题、结构、限制", "事实数字要回源", "输出要有验收标准"],
    opportunities: ["快速生成可传播图片", "为 Home 和详情页提供视觉资产"],
    risks: ["中文排版错误", "事实变形", "视觉风格不稳定"],
    next_steps: ["复制 prompt 模板", "生成一张封面", "按 checklist 验收"],
    related_ids: ["model-visual-briefing", "article-visual-briefing-system"],
    outcome: "生成一张可发布的 AI Brief 视觉图",
    prerequisites: ["已有一条结构化 Brief", "明确来源链接"],
    prompts: ["生成一张中文 AI 简报封面图，包含影响、行动、风险三层信息。"],
    checklist: ["标题可读", "结论清楚", "来源可追溯", "没有未经核实数字"],
    validation_methods: ["5 秒内能看懂主题", "人工核对来源", "移动端缩略图仍可读"],
  },
  {
    id: "guide-agent-workflow-eval",
    slug: "agent-workflow-eval",
    title: "用真实任务评估 Agent Workflow",
    summary: "用一个可回滚的业务流程测试 Agent 是否真的能稳定完成工作。",
    one_sentence_takeaway: "Agent workflow 的验收标准是可完成、可复盘、可回滚。",
    why_it_matters: "没有验收标准的 Agent demo 很容易误导团队决策。",
    content_type: "guide",
    category: "agent",
    tags: ["Agent", "Workflow", "Safety"],
    target_audience: ["developer", "operator", "enterprise"],
    source_name: "AI-brief Playbooks",
    source_url: "https://example.com/agent-workflow-eval",
    published_at: "2026-05-06",
    collected_at: collectedAt,
    language: "zh",
    reading_time_minutes: 8,
    status: "published",
    readability_score: 86,
    impact_score: 85,
    actionability_score: 92,
    confidence_score: 79,
    difficulty: "intermediate",
    recommended_action: "save",
    key_facts: ["要用真实任务", "日志和回滚是验收的一部分", "低风险流程先试"],
    opportunities: ["把重复运营流程自动化", "建立 Agent 评测模板"],
    risks: ["错误执行真实操作", "没有回滚", "日志不足"],
    next_steps: ["选择低风险流程", "定义成功标准", "跑一次 dry-run"],
    related_ids: ["news-enterprise-agent-workflows", "tool-workflow-automation-stack"],
    outcome: "得到一个 Agent workflow 是否可用的判断",
    prerequisites: ["一个低风险流程", "测试账号", "回滚方案"],
    prompts: ["请执行 dry-run，只输出计划和风险，不要真实写入。"],
    checklist: ["输入清楚", "输出可验收", "有日志", "有回滚", "失败模式已记录"],
    validation_methods: ["dry-run 结果符合预期", "真实执行不越权", "失败后可恢复"],
  },
  {
    id: "course-ai-coding-builder",
    slug: "ai-coding-builder-path",
    title: "AI Coding Builder 学习路径",
    summary: "面向开发者的学习路径，覆盖模型选择、Agent 工具、测试、代码 review 和部署。",
    one_sentence_takeaway: "AI Coding 的学习目标是能安全地交付代码改动。",
    why_it_matters: "开发者需要从提示技巧升级到工程化工作流。",
    content_type: "course",
    category: "learn",
    tags: ["AI Coding", "Agent"],
    target_audience: ["developer"],
    source_name: "AI-brief Learn",
    source_url: "https://example.com/ai-coding-builder-path",
    published_at: "2026-05-07",
    collected_at: collectedAt,
    language: "zh",
    reading_time_minutes: 5,
    status: "published",
    readability_score: 89,
    impact_score: 81,
    actionability_score: 88,
    confidence_score: 76,
    difficulty: "intermediate",
    recommended_action: "save",
    key_facts: ["要学习模型评估", "要理解测试和回滚", "要建立安全边界"],
    opportunities: ["提升开发效率", "形成可复用工作流"],
    risks: ["过度依赖自动改代码", "忽略测试"],
    next_steps: ["完成一个带测试的小改动", "记录 AI 工具失败模式"],
    related_ids: ["tool-ai-coding-suite", "guide-model-migration-checklist"],
    provider: "AI-brief Learn",
    duration: "2 weeks",
    learning_outcomes: ["完成 AI 辅助 bugfix", "建立模型选择表", "写出代码 review checklist"],
    project_based: true,
  },
  {
    id: "course-rag-engineer",
    slug: "rag-engineer-path",
    title: "RAG 工程师学习路径",
    summary: "面向需要构建知识库和检索系统的开发者，覆盖数据清洗、召回、评估和上线监控。",
    one_sentence_takeaway: "RAG 学习应该围绕可评估的问答质量，而不是只接向量库。",
    why_it_matters: "企业知识库项目失败常常不是模型问题，而是评估和数据治理缺失。",
    content_type: "course",
    category: "learn",
    tags: ["RAG", "Research", "Business"],
    target_audience: ["developer", "enterprise"],
    source_name: "AI-brief Learn",
    source_url: "https://example.com/rag-engineer-path",
    published_at: "2026-05-06",
    collected_at: collectedAt,
    language: "zh",
    reading_time_minutes: 5,
    status: "published",
    readability_score: 86,
    impact_score: 79,
    actionability_score: 84,
    confidence_score: 74,
    difficulty: "advanced",
    recommended_action: "read",
    key_facts: ["评估集是核心资产", "数据清洗影响召回质量", "上线后需要监控"],
    opportunities: ["构建内部知识库", "降低客服和研究成本"],
    risks: ["幻觉被误认为检索结果", "数据权限不清"],
    next_steps: ["收集 30 个真实问题", "建立评估集", "跑 baseline"],
    related_ids: ["model-long-context-chinese", "tool-local-ai-runtime"],
    provider: "AI-brief Learn",
    duration: "3 weeks",
    learning_outcomes: ["建立 RAG baseline", "设计评估集", "写出监控指标"],
    project_based: true,
  },
  {
    id: "course-enterprise-ai-adoption",
    slug: "enterprise-ai-adoption-path",
    title: "企业 AI 采用者学习路径",
    summary: "面向采购、运营和管理者，覆盖工具评估、权限、合规、ROI 和试点设计。",
    one_sentence_takeaway: "企业 AI 学习目标是做出可控试点，而不是追逐工具清单。",
    why_it_matters: "企业采用 AI 的瓶颈往往是流程、风险和组织协作。",
    content_type: "course",
    category: "learn",
    tags: ["Business", "Safety", "Workflow"],
    target_audience: ["enterprise", "operator", "pm"],
    source_name: "AI-brief Learn",
    source_url: "https://example.com/enterprise-ai-adoption-path",
    published_at: "2026-05-05",
    collected_at: collectedAt,
    language: "zh",
    reading_time_minutes: 5,
    status: "published",
    readability_score: 91,
    impact_score: 82,
    actionability_score: 86,
    confidence_score: 78,
    difficulty: "beginner",
    recommended_action: "save",
    key_facts: ["试点要有成功标准", "权限和数据边界先于规模化", "ROI 需要可度量"],
    opportunities: ["设计低风险 AI 试点", "建立采购 checklist"],
    risks: ["工具先行导致流程失控", "忽略合规和审计"],
    next_steps: ["选一个低风险场景", "定义 ROI 指标", "列出权限边界"],
    related_ids: ["news-ai-risk-procurement", "integration-mcp-permission-check"],
    provider: "AI-brief Learn",
    duration: "1 week",
    learning_outcomes: ["写出 AI 试点计划", "完成工具采购评估", "定义上线风险清单"],
    project_based: true,
  },
];
