import type { ContentTag, ContentType } from "../content/types";
import type { Source } from "./index";

export type IngestionColumn = "news" | "models" | "projects" | "skills" | "articles" | "courses";

export type SourceAdapter =
  | "rss_feed"
  | "web_index"
  | "github_trending"
  | "github_search"
  | "github_code_search"
  | "huggingface_models"
  | "huggingface_spaces"
  | "product_hunt"
  | "hn_discovery"
  | "paper_index"
  | "course_page";

export type SourceRole = "primary" | "secondary" | "benchmark" | "official" | "discovery_signal";
export const sourceTiers = [
  "core_discovery",
  "official_primary",
  "benchmark_data",
  "weekly_deep",
  "triggered_news",
  "deep_enrichment",
] as const;
export type SourceTier = (typeof sourceTiers)[number];

export type Cadence = "daily" | "weekly" | "monthly" | "manual";

export interface ColumnIngestionPolicy {
  column: IngestionColumn;
  raw_limit: number;
  selected_limit: number;
  minimum_published: number;
  minimum_source_diversity: number;
  cadence: Cadence;
  output_goal: string;
  include_keywords: string[];
  exclude_keywords: string[];
}

export interface ColumnSourceConfig extends Source {
  column: IngestionColumn;
  role: SourceRole;
  adapter: SourceAdapter;
  raw_limit: number;
  selected_limit: number;
  cadence: Cadence;
  output_goal: string;
  include_keywords: string[];
  exclude_keywords: string[];
  source_tier: SourceTier;
  default_content_type: ContentType;
  default_tags: ContentTag[];
  query?: string;
  period?: "daily" | "weekly" | "monthly";
}

export const ingestionColumns = ["news", "models", "projects", "skills", "articles", "courses"] as const;

const commonAiIncludes = ["AI", "artificial intelligence", "LLM", "model", "agent", "OpenAI", "Claude", "Gemini"];

export const columnIngestionPolicies: Record<IngestionColumn, ColumnIngestionPolicy> = {
  news: {
    column: "news",
    raw_limit: 80,
    selected_limit: 10,
    minimum_published: 3,
    minimum_source_diversity: 2,
    cadence: "daily",
    output_goal: "抓取真正的 AI story：公司、政策、监管、融资、合作、安全事故、产业采用和平台级变化，不抓普通技术教程。",
    include_keywords: [
      ...commonAiIncludes,
      "regulation",
      "lawsuit",
      "partnership",
      "funding",
      "acquisition",
      "safety",
      "policy",
      "chip",
      "compute",
      "enterprise adoption",
    ],
    exclude_keywords: ["tutorial", "how to", "guide", "benchmark code", "paper abstract", "GitHub repository", "course", "webinar", "severance", "laid-off", "layoffs", "workers tried to negotiate"],
  },
  models: {
    column: "models",
    raw_limit: 70,
    selected_limit: 10,
    minimum_published: 3,
    minimum_source_diversity: 2,
    cadence: "daily",
    output_goal: "抓取模型能力变化、价格、速度、上下文、工具调用、多模态和榜单变化，用于判断是否值得切换或测试。",
    include_keywords: [
      "model",
      "benchmark",
      "leaderboard",
      "pricing",
      "latency",
      "context window",
      "tool use",
      "reasoning",
      "multimodal",
      "API",
      "OpenRouter",
      "LMArena",
      "Artificial Analysis",
    ],
    exclude_keywords: [
      "funding",
      "hiring",
      "generic company news",
      "opinion only",
      "tutorial",
      "course",
      "usage tracking",
      "headers",
      "documentation page",
      "running codex safely",
      "testing ads",
      "advertising",
      "customer story",
      "ChatGPT Enterprise",
      "uses OpenAI",
      "frontier firms",
      "pulling ahead",
      "software development with Codex",
      "helps bankers",
      "AI transformation",
      "partnership",
    ],
  },
  projects: {
    column: "projects",
    raw_limit: 120,
    selected_limit: 15,
    minimum_published: 4,
    minimum_source_diversity: 2,
    cadence: "daily",
    output_goal: "抓取可运行工具、开源项目、产品 demo 和社区热度项目，重点看解决什么问题、是否可安装、是否值得进工具箱。",
    include_keywords: ["agent", "LLM", "RAG", "MCP", "AI coding", "workflow", "tool", "assistant", "local AI", "prompt", "multimodal"],
    exclude_keywords: ["awesome list", "paper list", "course list", "newsletter", "job board", "crypto unrelated"],
  },
  skills: {
    column: "skills",
    raw_limit: 80,
    selected_limit: 10,
    minimum_published: 3,
    minimum_source_diversity: 2,
    cadence: "daily",
    output_goal: "抓取可安装或可抽取的 agent behavior packs：SKILL.md、CLAUDE.md、MCP server、Cursor rules、hooks 和 workflow rules。",
    include_keywords: ["SKILL.md", "CLAUDE.md", "MCP server", "Cursor rules", "hooks", "agent skill", "rules", "workflow", "prompt pack"],
    exclude_keywords: ["generic AI SaaS", "landing page", "plain prompt collection", "course", "unrelated dotfiles"],
  },
  articles: {
    column: "articles",
    raw_limit: 90,
    selected_limit: 10,
    minimum_published: 3,
    minimum_source_diversity: 2,
    cadence: "daily",
    output_goal: "抓高质量文章、厂商技术博客、顶会论文和研究解读；HN 只能做发现信号，不能直接当主源。",
    include_keywords: ["paper", "research", "evaluation", "method", "dataset", "benchmark", "architecture", "agent", "LLM", "alignment"],
    exclude_keywords: ["low-effort news", "press release only", "course catalog", "generic startup launch", "HN discussion only"],
  },
  courses: {
    column: "courses",
    raw_limit: 30,
    selected_limit: 5,
    minimum_published: 2,
    minimum_source_diversity: 2,
    cadence: "weekly",
    output_goal: "周更可信课程源，只判断适合谁、能做出什么、时间成本、项目产出和现在是否值得学。",
    include_keywords: ["course", "learn", "hands-on", "project", "certificate", "AI", "LLM", "agent", "RAG", "machine learning"],
    exclude_keywords: ["event recap", "marketing ebook", "sales page only", "unrelated course"],
  },
};

function withPolicy(
  source: Omit<ColumnSourceConfig, "raw_limit" | "selected_limit" | "cadence" | "output_goal" | "include_keywords" | "exclude_keywords" | "source_tier"> &
    Partial<Pick<ColumnSourceConfig, "raw_limit" | "selected_limit" | "cadence" | "output_goal" | "include_keywords" | "exclude_keywords" | "source_tier">>,
): ColumnSourceConfig {
  const policy = columnIngestionPolicies[source.column];
  return {
    ...source,
    raw_limit: source.raw_limit ?? policy.raw_limit,
    selected_limit: source.selected_limit ?? policy.selected_limit,
    cadence: source.cadence ?? policy.cadence,
    output_goal: source.output_goal ?? policy.output_goal,
    include_keywords: source.include_keywords ?? policy.include_keywords,
    exclude_keywords: source.exclude_keywords ?? policy.exclude_keywords,
    source_tier: source.source_tier ?? inferSourceTier(source),
  };
}

function inferSourceTier(source: Pick<ColumnSourceConfig, "column" | "role" | "source_type">): SourceTier {
  if (source.role === "benchmark") return "benchmark_data";
  if (source.role === "official") return "official_primary";
  if (source.column === "models" && source.source_type === "official") return "official_primary";
  if (source.column === "skills" || source.column === "courses") return "weekly_deep";
  if (source.column === "articles") return source.role === "discovery_signal" ? "deep_enrichment" : "weekly_deep";
  return "core_discovery";
}

export const columnSourceConfigs: ColumnSourceConfig[] = [
  withPolicy({
    id: "reuters-ai",
    name: "Reuters AI",
    url: "https://www.reuters.com/technology/artificial-intelligence/",
    source_type: "media",
    language: "en",
    reliability_level: 5,
    enabled: false,
    column: "news",
    role: "primary",
    adapter: "web_index",
    default_content_type: "news",
    default_tags: ["Business"],
    source_tier: "triggered_news",
  }),
  withPolicy({
    id: "ap-ai",
    name: "AP Artificial Intelligence",
    url: "https://apnews.com/hub/artificial-intelligence",
    source_type: "media",
    language: "en",
    reliability_level: 5,
    enabled: false,
    column: "news",
    role: "primary",
    adapter: "web_index",
    default_content_type: "news",
    default_tags: ["Business", "Safety"],
    source_tier: "triggered_news",
  }),
  withPolicy({
    id: "financial-times-ai",
    name: "Financial Times AI",
    url: "https://www.ft.com/artificial-intelligence",
    source_type: "media",
    language: "en",
    reliability_level: 5,
    enabled: false,
    column: "news",
    role: "primary",
    adapter: "web_index",
    default_content_type: "news",
    default_tags: ["Business"],
    source_tier: "triggered_news",
  }),
  withPolicy({
    id: "bloomberg-ai",
    name: "Bloomberg AI",
    url: "https://www.bloomberg.com/technology",
    source_type: "media",
    language: "en",
    reliability_level: 5,
    enabled: false,
    column: "news",
    role: "primary",
    adapter: "web_index",
    default_content_type: "news",
    default_tags: ["Business"],
    source_tier: "triggered_news",
  }),
  withPolicy({
    id: "wsj-ai",
    name: "WSJ AI",
    url: "https://www.wsj.com/tech/ai",
    source_type: "media",
    language: "en",
    reliability_level: 5,
    enabled: false,
    column: "news",
    role: "primary",
    adapter: "web_index",
    default_content_type: "news",
    default_tags: ["Business"],
    source_tier: "triggered_news",
  }),
  withPolicy({
    id: "the-information-ai",
    name: "The Information AI",
    url: "https://www.theinformation.com/features/artificial-intelligence",
    source_type: "media",
    language: "en",
    reliability_level: 5,
    enabled: false,
    column: "news",
    role: "primary",
    adapter: "web_index",
    default_content_type: "news",
    default_tags: ["Business"],
    source_tier: "triggered_news",
  }),
  withPolicy({
    id: "axios-ai",
    name: "Axios AI",
    url: "https://www.axios.com/technology/artificial-intelligence",
    source_type: "media",
    language: "en",
    reliability_level: 4,
    enabled: false,
    column: "news",
    role: "primary",
    adapter: "web_index",
    default_content_type: "news",
    default_tags: ["Business"],
    source_tier: "triggered_news",
  }),
  withPolicy({
    id: "techcrunch-ai",
    name: "TechCrunch AI",
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    source_type: "media",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "news",
    role: "primary",
    adapter: "rss_feed",
    default_content_type: "news",
    default_tags: ["Business"],
  }),
  withPolicy({
    id: "mit-tech-review-ai",
    name: "MIT Technology Review AI",
    url: "https://www.technologyreview.com/topic/artificial-intelligence/feed/",
    source_type: "media",
    language: "en",
    reliability_level: 5,
    enabled: true,
    column: "news",
    role: "primary",
    adapter: "rss_feed",
    default_content_type: "news",
    default_tags: ["Business", "Research"],
    selected_limit: 2,
  }),
  withPolicy({
    id: "venturebeat-ai",
    name: "VentureBeat AI",
    url: "https://venturebeat.com/category/ai/feed/",
    source_type: "media",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "news",
    role: "primary",
    adapter: "rss_feed",
    default_content_type: "news",
    default_tags: ["Business"],
    selected_limit: 2,
  }),
  withPolicy({
    id: "google-news-ai",
    name: "Google News AI",
    url: "https://news.google.com/rss/search?q=artificial%20intelligence%20OR%20OpenAI%20OR%20Anthropic%20OR%20AI%20regulation%20when:2d&hl=en-US&gl=US&ceid=US:en",
    source_type: "community",
    language: "en",
    reliability_level: 3,
    enabled: false,
    column: "news",
    role: "discovery_signal",
    adapter: "rss_feed",
    default_content_type: "news",
    default_tags: ["Business"],
    selected_limit: 2,
    source_tier: "deep_enrichment",
  }),
  withPolicy({
    id: "the-verge-ai",
    name: "The Verge AI",
    url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    source_type: "media",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "news",
    role: "primary",
    adapter: "rss_feed",
    default_content_type: "news",
    default_tags: ["Business"],
  }),
  withPolicy({
    id: "guardian-ai",
    name: "The Guardian AI",
    url: "https://www.theguardian.com/technology/artificialintelligenceai/rss",
    source_type: "media",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "news",
    role: "primary",
    adapter: "rss_feed",
    default_content_type: "news",
    default_tags: ["Business", "Safety"],
    selected_limit: 1,
  }),
  withPolicy({
    id: "techxplore-ai",
    name: "Tech Xplore AI",
    url: "https://techxplore.com/rss-feed/machine-learning-ai-news/",
    source_type: "media",
    language: "en",
    reliability_level: 3,
    enabled: true,
    column: "news",
    role: "secondary",
    adapter: "rss_feed",
    default_content_type: "news",
    default_tags: ["Research", "Business"],
    selected_limit: 1,
  }),
  withPolicy({
    id: "wired-ai",
    name: "Wired AI",
    url: "https://www.wired.com/feed/tag/ai/latest/rss",
    source_type: "media",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "news",
    role: "primary",
    adapter: "rss_feed",
    default_content_type: "news",
    default_tags: ["Business", "Safety"],
  }),
  withPolicy({
    id: "nist-ai",
    name: "NIST AI",
    url: "https://www.nist.gov/news-events/news-updates/topic/2753736",
    source_type: "official",
    language: "en",
    reliability_level: 5,
    enabled: false,
    column: "news",
    role: "official",
    adapter: "web_index",
    default_content_type: "news",
    default_tags: ["Safety"],
    selected_limit: 1,
  }),
  withPolicy({
    id: "caisi",
    name: "CAISI",
    url: "https://www.nist.gov/aisi",
    source_type: "official",
    language: "en",
    reliability_level: 5,
    enabled: false,
    column: "news",
    role: "official",
    adapter: "web_index",
    default_content_type: "news",
    default_tags: ["Safety"],
  }),
  withPolicy({
    id: "qbitai-news",
    name: "量子位 AI News",
    url: "https://www.qbitai.com/feed",
    source_type: "media",
    language: "zh",
    reliability_level: 3,
    enabled: true,
    column: "news",
    role: "secondary",
    adapter: "rss_feed",
    default_content_type: "news",
    default_tags: ["China", "Business"],
  }),

  withPolicy({
    id: "openai-models",
    name: "OpenAI News",
    url: "https://openai.com/news/rss.xml",
    source_type: "official",
    language: "en",
    reliability_level: 5,
    enabled: true,
    column: "models",
    role: "official",
    adapter: "rss_feed",
    default_content_type: "model",
    default_tags: ["Agent", "Multimodal", "Research"],
  }),
  withPolicy({
    id: "anthropic-models",
    name: "Anthropic News",
    url: "https://www.anthropic.com/news",
    source_type: "official",
    language: "en",
    reliability_level: 5,
    enabled: true,
    column: "models",
    role: "official",
    adapter: "web_index",
    default_content_type: "model",
    default_tags: ["Agent", "Safety"],
  }),
  withPolicy({
    id: "google-deepmind-models",
    name: "Google DeepMind Blog",
    url: "https://deepmind.google/blog/rss.xml",
    source_type: "official",
    language: "en",
    reliability_level: 5,
    enabled: true,
    column: "models",
    role: "official",
    adapter: "rss_feed",
    default_content_type: "model",
    default_tags: ["Research", "Multimodal"],
  }),
  withPolicy({
    id: "mistral-models",
    name: "Mistral AI News",
    url: "https://mistral.ai/news",
    source_type: "official",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "models",
    role: "official",
    adapter: "web_index",
    default_content_type: "model",
    default_tags: ["Open Source", "Research"],
  }),
  withPolicy({
    id: "meta-ai-models",
    name: "Meta AI Blog",
    url: "https://ai.meta.com/blog/",
    source_type: "official",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "models",
    role: "official",
    adapter: "web_index",
    default_content_type: "model",
    default_tags: ["Open Source", "Research"],
  }),
  withPolicy({
    id: "deepseek-models",
    name: "DeepSeek",
    url: "https://www.deepseek.com/",
    source_type: "official",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "models",
    role: "official",
    adapter: "web_index",
    default_content_type: "model",
    default_tags: ["Research"],
  }),
  withPolicy({
    id: "qwen-models",
    name: "Qwen Blog",
    url: "https://qwenlm.github.io/blog/",
    source_type: "official",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "models",
    role: "official",
    adapter: "web_index",
    default_content_type: "model",
    default_tags: ["Open Source", "China"],
  }),
  withPolicy({
    id: "artificial-analysis",
    name: "Artificial Analysis",
    url: "https://artificialanalysis.ai/leaderboards/models",
    source_type: "community",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "models",
    role: "benchmark",
    adapter: "web_index",
    default_content_type: "model",
    default_tags: ["Research"],
  }),
  withPolicy({
    id: "lmarena",
    name: "LMArena",
    url: "https://lmarena.ai/leaderboard",
    source_type: "community",
    language: "en",
    reliability_level: 4,
    enabled: false,
    column: "models",
    role: "benchmark",
    adapter: "web_index",
    default_content_type: "model",
    default_tags: ["Research"],
  }),
  withPolicy({
    id: "openrouter-rankings",
    name: "OpenRouter Rankings",
    url: "https://openrouter.ai/rankings",
    source_type: "community",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "models",
    role: "benchmark",
    adapter: "web_index",
    default_content_type: "model",
    default_tags: ["Business", "Research"],
  }),

  withPolicy({
    id: "github-trending-daily",
    name: "GitHub Trending Daily",
    url: "https://github.com/trending?since=daily",
    source_type: "github",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "projects",
    role: "primary",
    adapter: "github_trending",
    period: "daily",
    default_content_type: "project",
    default_tags: ["Open Source"],
    selected_limit: 3,
  }),
  withPolicy({
    id: "github-trending-weekly",
    name: "GitHub Trending Weekly",
    url: "https://github.com/trending?since=weekly",
    source_type: "github",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "projects",
    role: "primary",
    adapter: "github_trending",
    period: "weekly",
    default_content_type: "project",
    default_tags: ["Open Source"],
    selected_limit: 3,
  }),
  withPolicy({
    id: "github-trending-monthly",
    name: "GitHub Trending Monthly",
    url: "https://github.com/trending?since=monthly",
    source_type: "github",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "projects",
    role: "primary",
    adapter: "github_trending",
    period: "monthly",
    default_content_type: "project",
    default_tags: ["Open Source"],
    selected_limit: 3,
  }),
  withPolicy({
    id: "github-ai-topic-search",
    name: "GitHub AI Topic Search",
    url: "https://api.github.com/search/repositories",
    source_type: "github",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "projects",
    role: "primary",
    adapter: "github_search",
    query: "topic:ai-agent stars:>20 OR topic:large-language-models stars:>50 OR topic:rag stars:>50 OR topic:generative-ai stars:>100 OR topic:ai-coding stars:>20",
    default_content_type: "project",
    default_tags: ["Open Source"],
    selected_limit: 3,
  }),
  withPolicy({
    id: "huggingface-spaces",
    name: "Hugging Face Spaces",
    url: "https://huggingface.co/api/spaces?sort=likes&direction=-1",
    source_type: "community",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "projects",
    role: "secondary",
    adapter: "huggingface_spaces",
    default_content_type: "project",
    default_tags: ["Open Source", "Multimodal"],
    selected_limit: 2,
  }),
  withPolicy({
    id: "huggingface-trending-models",
    name: "Hugging Face Trending Models",
    url: "https://huggingface.co/api/models?sort=likes&direction=-1",
    source_type: "community",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "projects",
    role: "secondary",
    adapter: "huggingface_models",
    default_content_type: "project",
    default_tags: ["Open Source", "Research"],
    selected_limit: 2,
  }),
  withPolicy({
    id: "product-hunt-ai",
    name: "Product Hunt AI",
    url: "https://www.producthunt.com/categories/ai-software",
    source_type: "community",
    language: "en",
    reliability_level: 3,
    enabled: false,
    column: "projects",
    role: "discovery_signal",
    adapter: "product_hunt",
    default_content_type: "tool",
    default_tags: ["Business"],
    selected_limit: 1,
    source_tier: "deep_enrichment",
  }),
  withPolicy({
    id: "show-hn-ai",
    name: "Show HN AI",
    url: "https://hn.algolia.com/api/v1/search_by_date?query=Show%20HN%20AI&tags=story",
    source_type: "community",
    language: "en",
    reliability_level: 3,
    enabled: true,
    column: "projects",
    role: "discovery_signal",
    adapter: "hn_discovery",
    query: "Show HN AI",
    default_content_type: "tool",
    default_tags: ["Business"],
    selected_limit: 1,
  }),

  withPolicy({
    id: "github-skill-md",
    name: "GitHub SKILL.md Search",
    url: "https://api.github.com/search/code",
    source_type: "github",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "skills",
    role: "primary",
    adapter: "github_code_search",
    query: "filename:SKILL.md agent",
    default_content_type: "integration",
    default_tags: ["Agent", "AI Coding", "Workflow"],
    selected_limit: 2,
  }),
  withPolicy({
    id: "github-claude-md",
    name: "GitHub CLAUDE.md Search",
    url: "https://api.github.com/search/code",
    source_type: "github",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "skills",
    role: "primary",
    adapter: "github_code_search",
    query: "filename:CLAUDE.md agent workflow",
    default_content_type: "integration",
    default_tags: ["Agent", "AI Coding", "Workflow"],
    selected_limit: 2,
  }),
  withPolicy({
    id: "github-mcp-server",
    name: "GitHub MCP Server Search",
    url: "https://api.github.com/search/repositories",
    source_type: "github",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "skills",
    role: "primary",
    adapter: "github_search",
    query: "topic:mcp-server stars:>20 OR topic:model-context-protocol stars:>20 OR \"model context protocol\" agent stars:>50",
    default_content_type: "integration",
    default_tags: ["MCP", "Agent"],
    selected_limit: 2,
  }),
  withPolicy({
    id: "github-cursor-rules",
    name: "GitHub Cursor Rules Search",
    url: "https://api.github.com/search/code",
    source_type: "github",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "skills",
    role: "primary",
    adapter: "github_code_search",
    query: "filename:.cursorrules agent OR filename:.cursorrules claude OR path:.cursor/rules agent OR path:.cursor/rules workflow OR path:.cursor/rules mcp",
    default_content_type: "integration",
    default_tags: ["AI Coding", "Workflow"],
    selected_limit: 2,
  }),
  withPolicy({
    id: "github-agent-hooks",
    name: "GitHub Hooks Search",
    url: "https://api.github.com/search/repositories",
    source_type: "github",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "skills",
    role: "primary",
    adapter: "github_search",
    query: "agent hooks Claude Code Cursor stars:>20",
    default_content_type: "integration",
    default_tags: ["Agent", "Workflow"],
    selected_limit: 2,
  }),

  withPolicy({
    id: "huggingface-papers",
    name: "Hugging Face Papers",
    url: "https://huggingface.co/api/daily_papers",
    source_type: "paper",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "articles",
    role: "primary",
    adapter: "paper_index",
    default_content_type: "paper",
    default_tags: ["Research"],
  }),
  withPolicy({
    id: "huggingface-blog-articles",
    name: "Hugging Face Blog",
    url: "https://huggingface.co/blog/feed.xml",
    source_type: "community",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "articles",
    role: "primary",
    adapter: "rss_feed",
    default_content_type: "article",
    default_tags: ["Open Source", "Research"],
    selected_limit: 2,
  }),
  withPolicy({
    id: "google-research-blog",
    name: "Google Research Blog",
    url: "https://research.google/blog/rss/",
    source_type: "official",
    language: "en",
    reliability_level: 5,
    enabled: true,
    column: "articles",
    role: "primary",
    adapter: "rss_feed",
    default_content_type: "article",
    default_tags: ["Research"],
    selected_limit: 2,
  }),
  withPolicy({
    id: "bair-blog",
    name: "BAIR Blog",
    url: "https://bair.berkeley.edu/blog/feed.xml",
    source_type: "community",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "articles",
    role: "primary",
    adapter: "rss_feed",
    default_content_type: "article",
    default_tags: ["Research"],
    selected_limit: 1,
  }),
  withPolicy({
    id: "openreview-ai",
    name: "OpenReview",
    url: "https://openreview.net/",
    source_type: "paper",
    language: "en",
    reliability_level: 4,
    enabled: false,
    column: "articles",
    role: "primary",
    adapter: "paper_index",
    default_content_type: "paper",
    default_tags: ["Research"],
  }),
  withPolicy({
    id: "acl-anthology",
    name: "ACL Anthology",
    url: "https://aclanthology.org/",
    source_type: "paper",
    language: "en",
    reliability_level: 4,
    enabled: false,
    column: "articles",
    role: "primary",
    adapter: "paper_index",
    default_content_type: "paper",
    default_tags: ["Research"],
  }),
  withPolicy({
    id: "neurips-papers",
    name: "NeurIPS Papers",
    url: "https://papers.nips.cc/",
    source_type: "paper",
    language: "en",
    reliability_level: 4,
    enabled: false,
    column: "articles",
    role: "primary",
    adapter: "paper_index",
    default_content_type: "paper",
    default_tags: ["Research"],
  }),
  withPolicy({
    id: "icml-papers",
    name: "ICML Papers",
    url: "https://proceedings.mlr.press/",
    source_type: "paper",
    language: "en",
    reliability_level: 4,
    enabled: false,
    column: "articles",
    role: "primary",
    adapter: "paper_index",
    default_content_type: "paper",
    default_tags: ["Research"],
  }),
  withPolicy({
    id: "iclr-openreview",
    name: "ICLR OpenReview",
    url: "https://openreview.net/group?id=ICLR.cc/2026/Conference",
    source_type: "paper",
    language: "en",
    reliability_level: 4,
    enabled: false,
    column: "articles",
    role: "primary",
    adapter: "paper_index",
    default_content_type: "paper",
    default_tags: ["Research"],
  }),
  withPolicy({
    id: "papers-with-code",
    name: "Papers with Code",
    url: "https://paperswithcode.com/",
    source_type: "paper",
    language: "en",
    reliability_level: 4,
    enabled: false,
    column: "articles",
    role: "primary",
    adapter: "paper_index",
    default_content_type: "paper",
    default_tags: ["Research", "Open Source"],
  }),
  withPolicy({
    id: "filtered-arxiv-ai",
    name: "Filtered arXiv AI",
    url: "https://export.arxiv.org/api/query",
    source_type: "paper",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "articles",
    role: "primary",
    adapter: "paper_index",
    query: "cat:cs.AI OR cat:cs.CL OR cat:cs.LG",
    default_content_type: "paper",
    default_tags: ["Research"],
  }),
  withPolicy({
    id: "hn-ai-discovery",
    name: "Hacker News AI Discovery",
    url: "https://hn.algolia.com/api/v1/search_by_date?query=AI&tags=story",
    source_type: "community",
    language: "en",
    reliability_level: 3,
    enabled: false,
    column: "articles",
    role: "discovery_signal",
    adapter: "hn_discovery",
    query: "AI",
    default_content_type: "article",
    default_tags: ["Business", "Research"],
    source_tier: "deep_enrichment",
  }),

  withPolicy({
    id: "deeplearning-ai-courses",
    name: "DeepLearning.AI Courses",
    url: "https://www.deeplearning.ai/courses/",
    source_type: "course",
    language: "en",
    reliability_level: 4,
    enabled: false,
    column: "courses",
    role: "primary",
    adapter: "course_page",
    default_content_type: "course",
    default_tags: ["Research", "Business"],
  }),
  withPolicy({
    id: "huggingface-llm-course",
    name: "Hugging Face LLM Course",
    url: "https://huggingface.co/learn/llm-course",
    source_type: "course",
    language: "en",
    reliability_level: 4,
    enabled: true,
    column: "courses",
    role: "primary",
    adapter: "course_page",
    default_content_type: "course",
    default_tags: ["Open Source", "Research"],
  }),
  withPolicy({
    id: "microsoft-generative-ai-fundamentals",
    name: "Microsoft Learn Generative AI Fundamentals",
    url: "https://learn.microsoft.com/en-us/training/modules/fundamentals-generative-ai/",
    source_type: "course",
    language: "en",
    reliability_level: 5,
    enabled: true,
    column: "courses",
    role: "primary",
    adapter: "course_page",
    default_content_type: "course",
    default_tags: ["Business", "Agent"],
  }),
  withPolicy({
    id: "openai-academy",
    name: "OpenAI Academy",
    url: "https://academy.openai.com/",
    source_type: "course",
    language: "en",
    reliability_level: 4,
    enabled: false,
    column: "courses",
    role: "primary",
    adapter: "course_page",
    default_content_type: "course",
    default_tags: ["Agent", "Business"],
  }),
  withPolicy({
    id: "fast-ai",
    name: "fast.ai",
    url: "https://www.fast.ai/",
    source_type: "course",
    language: "en",
    reliability_level: 4,
    enabled: false,
    column: "courses",
    role: "primary",
    adapter: "course_page",
    default_content_type: "course",
    default_tags: ["Research"],
  }),
];

export function getEnabledSourcesForColumn(column: IngestionColumn, requestedTiers?: readonly (SourceTier | string)[]): ColumnSourceConfig[] {
  const tierSet = requestedTiers?.length ? new Set(requestedTiers) : undefined;
  return columnSourceConfigs.filter((source) => source.column === column && (source.enabled || tierSet?.has(source.source_tier)) && (!tierSet || tierSet.has(source.source_tier)));
}

export interface ColumnSourcePlan {
  columns: IngestionColumn[];
  sources: ColumnSourceConfig[];
}

export function createColumnSourcePlan(requestedColumns?: readonly (IngestionColumn | string)[], requestedTiers?: readonly (SourceTier | string)[]): ColumnSourcePlan {
  const allowed = new Set<IngestionColumn>(ingestionColumns);
  const allowedTiers = new Set<SourceTier>(sourceTiers);
  const tiers = requestedTiers
    ? [...new Set(requestedTiers.filter((tier): tier is SourceTier => allowedTiers.has(tier as SourceTier)))]
    : undefined;
  const columns = requestedColumns
    ? [...new Set(requestedColumns.filter((column): column is IngestionColumn => allowed.has(column as IngestionColumn)))]
    : [...ingestionColumns];
  return {
    columns,
    sources: columns.flatMap((column) => getEnabledSourcesForColumn(column, tiers)),
  };
}

export function shouldKeepCandidateForColumn(column: IngestionColumn, candidateText: string): boolean {
  const policy = columnIngestionPolicies[column];
  const text = candidateText.toLowerCase();
  const hasInclude = policy.include_keywords.some((keyword) => keywordMatches(text, keyword));
  const hasExclude = policy.exclude_keywords.some((keyword) => keywordMatches(text, keyword));
  return hasInclude && !hasExclude;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function keywordMatches(normalizedText: string, keyword: string): boolean {
  const normalizedKeyword = keyword.toLowerCase().trim();
  if (!normalizedKeyword) return false;

  // Short tokens such as "AI" and "LLM" must not match inside unrelated words
  // like "laid" or "allmeta". Longer phrases can safely use substring matching.
  if (/^[a-z0-9+#.-]{1,4}$/.test(normalizedKeyword)) {
    return new RegExp(`(^|[^a-z0-9])${escapeRegExp(normalizedKeyword)}([^a-z0-9]|$)`, "i").test(normalizedText);
  }

  return normalizedText.includes(normalizedKeyword);
}

export function buildCandidateFilterText(
  sourceName: string,
  row: { title?: string; summary?: string; source_text?: string; tags?: string[] },
): string {
  const sourceLinePattern =
    /^(feed source|source|web index source|index title|code search source|paper source|course source|product discovery source|discovery source):.*$/gim;
  const cleanedSourceText = (row.source_text ?? "")
    .replace(sourceLinePattern, " ")
    .replaceAll(sourceName, " ");
  return [row.title, row.summary, cleanedSourceText, (row.tags ?? []).join(" ")]
    .filter(Boolean)
    .join("\n")
    .replace(/\s+/g, " ")
    .trim();
}

export function getCandidateFetchLimitForSource(source: ColumnSourceConfig, requestedColumnLimit?: number): number {
  const sourceTarget = Math.max(1, source.selected_limit ?? requestedColumnLimit ?? 1);
  const columnTarget = requestedColumnLimit && requestedColumnLimit > 0 ? Math.max(1, requestedColumnLimit) : sourceTarget;
  const target = Math.min(sourceTarget, columnTarget);
  return Math.min(source.raw_limit ?? target, 30, Math.max(target * 4, target));
}
